### ISSUE TITLE
installing on macosx

### ISSUE THREAD

**Issue by mdesco** [scil-vital/TrackToLearn#29] opened 2023-05-27 14:05 UTC
Does not seem to work with python3.8. Breaks at the zipp install. 
ERROR: Ignored the following versions that require a different python version: 8.13.1 Requires-Python >=3.9; 8.13.2 Requires-Python >=3.9
ERROR: Could not find a version that satisfies the requirement torch==1.9.1+cu111 (from versions: 1.4.0, 1.5.0, 1.5.1, 1.6.0, 1.7.0, 1.7.1, 1.8.0, 1.8.1, 1.9.0, 1.9.1, 1.10.0, 1.10.1, 1.10.2, 1.11.0, 1.12.0, 1.12.1, 1.13.0, 1.13.1, 2.0.0, 2.0.1)
ERROR: No matching distribution found for torch==1.9.1+cu111

If I create another virtualenv with python3.10, it also breaks on zipp install and then tells me I need python < 3.9...

Don't know what to do with this but ideally, we would have a version of the code compatible with python3.10 like scilpy. Maybe Arnaud or Francois have some insights...

**Comment by AntoineTheb** [comment] 2023-05-27 14:44
pip's error message is misleading in this case. Since CUDA is not available on MacOS, the "+cu111" flag prevents pip from finding a suitable torch version. I will tweak the requirements.txt file to automatically install the CPU version for MacOS.

**Comment by AntoineTheb** [comment] 2023-05-27 14:46
I would also be weary of switching python versions for now. From my experience, the rng can be different between python version, which would hamper reproducibility. Maybe I could allow more python versions for tracking only.

**Comment by AntoineTheb** [comment] 2023-05-27 15:01
Otherwise of you want to test, you can remove the lines at the bottom of the requirements.txt file and run

```pip install torch==1.9.1 torchvision==0.10.1 torchaudio==0.9.1```

in your Python3.8 env instead. This should work.

**Comment by AntoineTheb** [comment] 2023-05-29 13:58
@mdesco Can you try #30 ? I don't have a macbook to test. Simply pulling the branch and installing as mentionned by the README should work.

**Comment by AntoineTheb** [comment] 2023-05-29 20:19
Should be fixed by #30 .

**Closed as completed by AntoineTheb** 2023-05-29 20:19 UTC
Labels: bug, documentation
